// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Companies: typeof import('./src/components/Companies.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    'Footer copy': typeof import('./src/components/Footer copy.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Me: typeof import('./src/components/Me.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
